//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  import type { TinaMarkdownContent } from 'tinacms/dist/rich-text';
/** Internal type. DO NOT USE DIRECTLY. */
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
/** Internal type. DO NOT USE DIRECTLY. */
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
  /** A rich-text document, renderable by TinaMarkdown */
  RichText: { input: TinaMarkdownContent; output: TinaMarkdownContent; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  page: Page;
  pageConnection: PageConnection;
  config: Config;
  configConnection: ConfigConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PageFilter>;
};


export type QueryConfigArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryConfigConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ConfigFilter>;
};

export type DocumentFilter = {
  page?: InputMaybe<PageFilter>;
  config?: InputMaybe<ConfigFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Page | Config | Folder;

export type PageBlocksHeroPrimaryAction = {
  __typename?: 'PageBlocksHeroPrimaryAction';
  label?: Maybe<Scalars['String']['output']>;
  link?: Maybe<Scalars['String']['output']>;
};

export type PageBlocksHeroSecondaryAction = {
  __typename?: 'PageBlocksHeroSecondaryAction';
  label?: Maybe<Scalars['String']['output']>;
  link?: Maybe<Scalars['String']['output']>;
};

export type PageBlocksHeroImage = {
  __typename?: 'PageBlocksHeroImage';
  src?: Maybe<Scalars['String']['output']>;
  alt?: Maybe<Scalars['String']['output']>;
};

export type PageBlocksHero = {
  __typename?: 'PageBlocksHero';
  eyebrow?: Maybe<Scalars['String']['output']>;
  headline?: Maybe<Scalars['String']['output']>;
  tagline?: Maybe<Scalars['String']['output']>;
  primaryAction?: Maybe<PageBlocksHeroPrimaryAction>;
  secondaryAction?: Maybe<PageBlocksHeroSecondaryAction>;
  image?: Maybe<PageBlocksHeroImage>;
};

export type PageBlocksRichText = {
  __typename?: 'PageBlocksRichText';
  eyebrow?: Maybe<Scalars['String']['output']>;
  headline?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['RichText']['output']>;
};

export type PageBlocksMediaImage = {
  __typename?: 'PageBlocksMediaImage';
  src?: Maybe<Scalars['String']['output']>;
  alt?: Maybe<Scalars['String']['output']>;
  caption?: Maybe<Scalars['String']['output']>;
};

export type PageBlocksMedia = {
  __typename?: 'PageBlocksMedia';
  image?: Maybe<PageBlocksMediaImage>;
  aspect?: Maybe<Scalars['String']['output']>;
};

export type PageBlocksCta = {
  __typename?: 'PageBlocksCta';
  headline?: Maybe<Scalars['String']['output']>;
  text?: Maybe<Scalars['String']['output']>;
  primaryLabel?: Maybe<Scalars['String']['output']>;
  primaryLink?: Maybe<Scalars['String']['output']>;
  secondaryLabel?: Maybe<Scalars['String']['output']>;
  secondaryLink?: Maybe<Scalars['String']['output']>;
};

export type PageBlocksGalleryImages = {
  __typename?: 'PageBlocksGalleryImages';
  src?: Maybe<Scalars['String']['output']>;
  alt?: Maybe<Scalars['String']['output']>;
  caption?: Maybe<Scalars['String']['output']>;
};

export type PageBlocksGallery = {
  __typename?: 'PageBlocksGallery';
  headline?: Maybe<Scalars['String']['output']>;
  images?: Maybe<Array<Maybe<PageBlocksGalleryImages>>>;
};

export type PageBlocksAccordionItems = {
  __typename?: 'PageBlocksAccordionItems';
  title?: Maybe<Scalars['String']['output']>;
  content?: Maybe<Scalars['RichText']['output']>;
};

export type PageBlocksAccordion = {
  __typename?: 'PageBlocksAccordion';
  headline?: Maybe<Scalars['String']['output']>;
  items?: Maybe<Array<Maybe<PageBlocksAccordionItems>>>;
};

export type PageBlocksStatsItems = {
  __typename?: 'PageBlocksStatsItems';
  value?: Maybe<Scalars['String']['output']>;
  label?: Maybe<Scalars['String']['output']>;
};

export type PageBlocksStats = {
  __typename?: 'PageBlocksStats';
  headline?: Maybe<Scalars['String']['output']>;
  items?: Maybe<Array<Maybe<PageBlocksStatsItems>>>;
};

export type PageBlocksTestimonialAvatar = {
  __typename?: 'PageBlocksTestimonialAvatar';
  src?: Maybe<Scalars['String']['output']>;
  alt?: Maybe<Scalars['String']['output']>;
};

export type PageBlocksTestimonial = {
  __typename?: 'PageBlocksTestimonial';
  quote?: Maybe<Scalars['String']['output']>;
  author?: Maybe<Scalars['String']['output']>;
  role?: Maybe<Scalars['String']['output']>;
  avatar?: Maybe<PageBlocksTestimonialAvatar>;
};

export type PageBlocksPricingTiers = {
  __typename?: 'PageBlocksPricingTiers';
  title?: Maybe<Scalars['String']['output']>;
  price?: Maybe<Scalars['String']['output']>;
  priceNote?: Maybe<Scalars['String']['output']>;
  desc?: Maybe<Scalars['String']['output']>;
  bullets?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  featured?: Maybe<Scalars['Boolean']['output']>;
  ctaLabel?: Maybe<Scalars['String']['output']>;
  ctaLink?: Maybe<Scalars['String']['output']>;
};

export type PageBlocksPricing = {
  __typename?: 'PageBlocksPricing';
  eyebrow?: Maybe<Scalars['String']['output']>;
  headline?: Maybe<Scalars['String']['output']>;
  subhead?: Maybe<Scalars['String']['output']>;
  accent?: Maybe<Scalars['String']['output']>;
  tiers?: Maybe<Array<Maybe<PageBlocksPricingTiers>>>;
  fine?: Maybe<Scalars['String']['output']>;
};

export type PageBlocks = PageBlocksHero | PageBlocksRichText | PageBlocksMedia | PageBlocksCta | PageBlocksGallery | PageBlocksAccordion | PageBlocksStats | PageBlocksTestimonial | PageBlocksPricing;

export type Page = Node & Document & {
  __typename?: 'Page';
  seoTitle: Scalars['String']['output'];
  blocks?: Maybe<Array<Maybe<PageBlocks>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type PageBlocksHeroPrimaryActionFilter = {
  label?: InputMaybe<StringFilter>;
  link?: InputMaybe<StringFilter>;
};

export type PageBlocksHeroSecondaryActionFilter = {
  label?: InputMaybe<StringFilter>;
  link?: InputMaybe<StringFilter>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type PageBlocksHeroImageFilter = {
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
};

export type PageBlocksHeroFilter = {
  eyebrow?: InputMaybe<StringFilter>;
  headline?: InputMaybe<StringFilter>;
  tagline?: InputMaybe<StringFilter>;
  primaryAction?: InputMaybe<PageBlocksHeroPrimaryActionFilter>;
  secondaryAction?: InputMaybe<PageBlocksHeroSecondaryActionFilter>;
  image?: InputMaybe<PageBlocksHeroImageFilter>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type PageBlocksRichTextFilter = {
  eyebrow?: InputMaybe<StringFilter>;
  headline?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type PageBlocksMediaImageFilter = {
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
  caption?: InputMaybe<StringFilter>;
};

export type PageBlocksMediaFilter = {
  image?: InputMaybe<PageBlocksMediaImageFilter>;
  aspect?: InputMaybe<StringFilter>;
};

export type PageBlocksCtaFilter = {
  headline?: InputMaybe<StringFilter>;
  text?: InputMaybe<StringFilter>;
  primaryLabel?: InputMaybe<StringFilter>;
  primaryLink?: InputMaybe<StringFilter>;
  secondaryLabel?: InputMaybe<StringFilter>;
  secondaryLink?: InputMaybe<StringFilter>;
};

export type PageBlocksGalleryImagesFilter = {
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
  caption?: InputMaybe<StringFilter>;
};

export type PageBlocksGalleryFilter = {
  headline?: InputMaybe<StringFilter>;
  images?: InputMaybe<PageBlocksGalleryImagesFilter>;
};

export type PageBlocksAccordionItemsFilter = {
  title?: InputMaybe<StringFilter>;
  content?: InputMaybe<RichTextFilter>;
};

export type PageBlocksAccordionFilter = {
  headline?: InputMaybe<StringFilter>;
  items?: InputMaybe<PageBlocksAccordionItemsFilter>;
};

export type PageBlocksStatsItemsFilter = {
  value?: InputMaybe<StringFilter>;
  label?: InputMaybe<StringFilter>;
};

export type PageBlocksStatsFilter = {
  headline?: InputMaybe<StringFilter>;
  items?: InputMaybe<PageBlocksStatsItemsFilter>;
};

export type PageBlocksTestimonialAvatarFilter = {
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
};

export type PageBlocksTestimonialFilter = {
  quote?: InputMaybe<StringFilter>;
  author?: InputMaybe<StringFilter>;
  role?: InputMaybe<StringFilter>;
  avatar?: InputMaybe<PageBlocksTestimonialAvatarFilter>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type PageBlocksPricingTiersFilter = {
  title?: InputMaybe<StringFilter>;
  price?: InputMaybe<StringFilter>;
  priceNote?: InputMaybe<StringFilter>;
  desc?: InputMaybe<StringFilter>;
  bullets?: InputMaybe<StringFilter>;
  featured?: InputMaybe<BooleanFilter>;
  ctaLabel?: InputMaybe<StringFilter>;
  ctaLink?: InputMaybe<StringFilter>;
};

export type PageBlocksPricingFilter = {
  eyebrow?: InputMaybe<StringFilter>;
  headline?: InputMaybe<StringFilter>;
  subhead?: InputMaybe<StringFilter>;
  accent?: InputMaybe<StringFilter>;
  tiers?: InputMaybe<PageBlocksPricingTiersFilter>;
  fine?: InputMaybe<StringFilter>;
};

export type PageBlocksFilter = {
  hero?: InputMaybe<PageBlocksHeroFilter>;
  richText?: InputMaybe<PageBlocksRichTextFilter>;
  media?: InputMaybe<PageBlocksMediaFilter>;
  cta?: InputMaybe<PageBlocksCtaFilter>;
  gallery?: InputMaybe<PageBlocksGalleryFilter>;
  accordion?: InputMaybe<PageBlocksAccordionFilter>;
  stats?: InputMaybe<PageBlocksStatsFilter>;
  testimonial?: InputMaybe<PageBlocksTestimonialFilter>;
  pricing?: InputMaybe<PageBlocksPricingFilter>;
};

export type PageFilter = {
  seoTitle?: InputMaybe<StringFilter>;
  blocks?: InputMaybe<PageBlocksFilter>;
};

export type PageConnectionEdges = {
  __typename?: 'PageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Page>;
};

export type PageConnection = Connection & {
  __typename?: 'PageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PageConnectionEdges>>>;
};

export type ConfigSeo = {
  __typename?: 'ConfigSeo';
  title: Scalars['String']['output'];
  description: Scalars['String']['output'];
};

export type ConfigNav = {
  __typename?: 'ConfigNav';
  title: Scalars['String']['output'];
  link: Scalars['String']['output'];
};

export type Config = Node & Document & {
  __typename?: 'Config';
  seo?: Maybe<ConfigSeo>;
  nav?: Maybe<Array<Maybe<ConfigNav>>>;
  footerNote?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ConfigSeoFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type ConfigNavFilter = {
  title?: InputMaybe<StringFilter>;
  link?: InputMaybe<StringFilter>;
};

export type ConfigFilter = {
  seo?: InputMaybe<ConfigSeoFilter>;
  nav?: InputMaybe<ConfigNavFilter>;
  footerNote?: InputMaybe<StringFilter>;
};

export type ConfigConnectionEdges = {
  __typename?: 'ConfigConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Config>;
};

export type ConfigConnection = Connection & {
  __typename?: 'ConfigConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ConfigConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updatePage: Page;
  createPage: Page;
  updateConfig: Config;
  createConfig: Config;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdatePageArgs = {
  relativePath: Scalars['String']['input'];
  params: PageMutation;
};


export type MutationCreatePageArgs = {
  relativePath: Scalars['String']['input'];
  params: PageMutation;
};


export type MutationUpdateConfigArgs = {
  relativePath: Scalars['String']['input'];
  params: ConfigMutation;
};


export type MutationCreateConfigArgs = {
  relativePath: Scalars['String']['input'];
  params: ConfigMutation;
};

export type DocumentUpdateMutation = {
  page?: InputMaybe<PageMutation>;
  config?: InputMaybe<ConfigMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  page?: InputMaybe<PageMutation>;
  config?: InputMaybe<ConfigMutation>;
};

export type PageBlocksHeroPrimaryActionMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  link?: InputMaybe<Scalars['String']['input']>;
};

export type PageBlocksHeroSecondaryActionMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  link?: InputMaybe<Scalars['String']['input']>;
};

export type PageBlocksHeroImageMutation = {
  src?: InputMaybe<Scalars['String']['input']>;
  alt?: InputMaybe<Scalars['String']['input']>;
};

export type PageBlocksHeroMutation = {
  eyebrow?: InputMaybe<Scalars['String']['input']>;
  headline?: InputMaybe<Scalars['String']['input']>;
  tagline?: InputMaybe<Scalars['String']['input']>;
  primaryAction?: InputMaybe<PageBlocksHeroPrimaryActionMutation>;
  secondaryAction?: InputMaybe<PageBlocksHeroSecondaryActionMutation>;
  image?: InputMaybe<PageBlocksHeroImageMutation>;
};

export type PageBlocksRichTextMutation = {
  eyebrow?: InputMaybe<Scalars['String']['input']>;
  headline?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['RichText']['input']>;
};

export type PageBlocksMediaImageMutation = {
  src?: InputMaybe<Scalars['String']['input']>;
  alt?: InputMaybe<Scalars['String']['input']>;
  caption?: InputMaybe<Scalars['String']['input']>;
};

export type PageBlocksMediaMutation = {
  image?: InputMaybe<PageBlocksMediaImageMutation>;
  aspect?: InputMaybe<Scalars['String']['input']>;
};

export type PageBlocksCtaMutation = {
  headline?: InputMaybe<Scalars['String']['input']>;
  text?: InputMaybe<Scalars['String']['input']>;
  primaryLabel?: InputMaybe<Scalars['String']['input']>;
  primaryLink?: InputMaybe<Scalars['String']['input']>;
  secondaryLabel?: InputMaybe<Scalars['String']['input']>;
  secondaryLink?: InputMaybe<Scalars['String']['input']>;
};

export type PageBlocksGalleryImagesMutation = {
  src?: InputMaybe<Scalars['String']['input']>;
  alt?: InputMaybe<Scalars['String']['input']>;
  caption?: InputMaybe<Scalars['String']['input']>;
};

export type PageBlocksGalleryMutation = {
  headline?: InputMaybe<Scalars['String']['input']>;
  images?: InputMaybe<Array<InputMaybe<PageBlocksGalleryImagesMutation>>>;
};

export type PageBlocksAccordionItemsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  content?: InputMaybe<Scalars['RichText']['input']>;
};

export type PageBlocksAccordionMutation = {
  headline?: InputMaybe<Scalars['String']['input']>;
  items?: InputMaybe<Array<InputMaybe<PageBlocksAccordionItemsMutation>>>;
};

export type PageBlocksStatsItemsMutation = {
  value?: InputMaybe<Scalars['String']['input']>;
  label?: InputMaybe<Scalars['String']['input']>;
};

export type PageBlocksStatsMutation = {
  headline?: InputMaybe<Scalars['String']['input']>;
  items?: InputMaybe<Array<InputMaybe<PageBlocksStatsItemsMutation>>>;
};

export type PageBlocksTestimonialAvatarMutation = {
  src?: InputMaybe<Scalars['String']['input']>;
  alt?: InputMaybe<Scalars['String']['input']>;
};

export type PageBlocksTestimonialMutation = {
  quote?: InputMaybe<Scalars['String']['input']>;
  author?: InputMaybe<Scalars['String']['input']>;
  role?: InputMaybe<Scalars['String']['input']>;
  avatar?: InputMaybe<PageBlocksTestimonialAvatarMutation>;
};

export type PageBlocksPricingTiersMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  price?: InputMaybe<Scalars['String']['input']>;
  priceNote?: InputMaybe<Scalars['String']['input']>;
  desc?: InputMaybe<Scalars['String']['input']>;
  bullets?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  featured?: InputMaybe<Scalars['Boolean']['input']>;
  ctaLabel?: InputMaybe<Scalars['String']['input']>;
  ctaLink?: InputMaybe<Scalars['String']['input']>;
};

export type PageBlocksPricingMutation = {
  eyebrow?: InputMaybe<Scalars['String']['input']>;
  headline?: InputMaybe<Scalars['String']['input']>;
  subhead?: InputMaybe<Scalars['String']['input']>;
  accent?: InputMaybe<Scalars['String']['input']>;
  tiers?: InputMaybe<Array<InputMaybe<PageBlocksPricingTiersMutation>>>;
  fine?: InputMaybe<Scalars['String']['input']>;
};

export type PageBlocksMutation = {
  hero?: InputMaybe<PageBlocksHeroMutation>;
  richText?: InputMaybe<PageBlocksRichTextMutation>;
  media?: InputMaybe<PageBlocksMediaMutation>;
  cta?: InputMaybe<PageBlocksCtaMutation>;
  gallery?: InputMaybe<PageBlocksGalleryMutation>;
  accordion?: InputMaybe<PageBlocksAccordionMutation>;
  stats?: InputMaybe<PageBlocksStatsMutation>;
  testimonial?: InputMaybe<PageBlocksTestimonialMutation>;
  pricing?: InputMaybe<PageBlocksPricingMutation>;
};

export type PageMutation = {
  seoTitle?: InputMaybe<Scalars['String']['input']>;
  blocks?: InputMaybe<Array<InputMaybe<PageBlocksMutation>>>;
};

export type ConfigSeoMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type ConfigNavMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  link?: InputMaybe<Scalars['String']['input']>;
};

export type ConfigMutation = {
  seo?: InputMaybe<ConfigSeoMutation>;
  nav?: InputMaybe<Array<InputMaybe<ConfigNavMutation>>>;
  footerNote?: InputMaybe<Scalars['String']['input']>;
};

export type StringFilter = {
  startsWith?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<string | null | undefined> | null | undefined;
};

export type PageBlocksHeroPrimaryActionFilter = {
  label?: StringFilter | null | undefined;
  link?: StringFilter | null | undefined;
};

export type PageBlocksHeroSecondaryActionFilter = {
  label?: StringFilter | null | undefined;
  link?: StringFilter | null | undefined;
};

export type ImageFilter = {
  startsWith?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<string | null | undefined> | null | undefined;
};

export type PageBlocksHeroImageFilter = {
  src?: ImageFilter | null | undefined;
  alt?: StringFilter | null | undefined;
};

export type PageBlocksHeroFilter = {
  eyebrow?: StringFilter | null | undefined;
  headline?: StringFilter | null | undefined;
  tagline?: StringFilter | null | undefined;
  primaryAction?: PageBlocksHeroPrimaryActionFilter | null | undefined;
  secondaryAction?: PageBlocksHeroSecondaryActionFilter | null | undefined;
  image?: PageBlocksHeroImageFilter | null | undefined;
};

export type RichTextFilter = {
  startsWith?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
};

export type PageBlocksRichTextFilter = {
  eyebrow?: StringFilter | null | undefined;
  headline?: StringFilter | null | undefined;
  body?: RichTextFilter | null | undefined;
};

export type PageBlocksMediaImageFilter = {
  src?: ImageFilter | null | undefined;
  alt?: StringFilter | null | undefined;
  caption?: StringFilter | null | undefined;
};

export type PageBlocksMediaFilter = {
  image?: PageBlocksMediaImageFilter | null | undefined;
  aspect?: StringFilter | null | undefined;
};

export type PageBlocksCtaFilter = {
  headline?: StringFilter | null | undefined;
  text?: StringFilter | null | undefined;
  primaryLabel?: StringFilter | null | undefined;
  primaryLink?: StringFilter | null | undefined;
  secondaryLabel?: StringFilter | null | undefined;
  secondaryLink?: StringFilter | null | undefined;
};

export type PageBlocksGalleryImagesFilter = {
  src?: ImageFilter | null | undefined;
  alt?: StringFilter | null | undefined;
  caption?: StringFilter | null | undefined;
};

export type PageBlocksGalleryFilter = {
  headline?: StringFilter | null | undefined;
  images?: PageBlocksGalleryImagesFilter | null | undefined;
};

export type PageBlocksAccordionItemsFilter = {
  title?: StringFilter | null | undefined;
  content?: RichTextFilter | null | undefined;
};

export type PageBlocksAccordionFilter = {
  headline?: StringFilter | null | undefined;
  items?: PageBlocksAccordionItemsFilter | null | undefined;
};

export type PageBlocksStatsItemsFilter = {
  value?: StringFilter | null | undefined;
  label?: StringFilter | null | undefined;
};

export type PageBlocksStatsFilter = {
  headline?: StringFilter | null | undefined;
  items?: PageBlocksStatsItemsFilter | null | undefined;
};

export type PageBlocksTestimonialAvatarFilter = {
  src?: ImageFilter | null | undefined;
  alt?: StringFilter | null | undefined;
};

export type PageBlocksTestimonialFilter = {
  quote?: StringFilter | null | undefined;
  author?: StringFilter | null | undefined;
  role?: StringFilter | null | undefined;
  avatar?: PageBlocksTestimonialAvatarFilter | null | undefined;
};

export type BooleanFilter = {
  eq?: boolean | null | undefined;
  exists?: boolean | null | undefined;
};

export type PageBlocksPricingTiersFilter = {
  title?: StringFilter | null | undefined;
  price?: StringFilter | null | undefined;
  priceNote?: StringFilter | null | undefined;
  desc?: StringFilter | null | undefined;
  bullets?: StringFilter | null | undefined;
  featured?: BooleanFilter | null | undefined;
  ctaLabel?: StringFilter | null | undefined;
  ctaLink?: StringFilter | null | undefined;
};

export type PageBlocksPricingFilter = {
  eyebrow?: StringFilter | null | undefined;
  headline?: StringFilter | null | undefined;
  subhead?: StringFilter | null | undefined;
  accent?: StringFilter | null | undefined;
  tiers?: PageBlocksPricingTiersFilter | null | undefined;
  fine?: StringFilter | null | undefined;
};

export type PageBlocksFilter = {
  hero?: PageBlocksHeroFilter | null | undefined;
  richText?: PageBlocksRichTextFilter | null | undefined;
  media?: PageBlocksMediaFilter | null | undefined;
  cta?: PageBlocksCtaFilter | null | undefined;
  gallery?: PageBlocksGalleryFilter | null | undefined;
  accordion?: PageBlocksAccordionFilter | null | undefined;
  stats?: PageBlocksStatsFilter | null | undefined;
  testimonial?: PageBlocksTestimonialFilter | null | undefined;
  pricing?: PageBlocksPricingFilter | null | undefined;
};

export type PageFilter = {
  seoTitle?: StringFilter | null | undefined;
  blocks?: PageBlocksFilter | null | undefined;
};

export type ConfigSeoFilter = {
  title?: StringFilter | null | undefined;
  description?: StringFilter | null | undefined;
};

export type ConfigNavFilter = {
  title?: StringFilter | null | undefined;
  link?: StringFilter | null | undefined;
};

export type ConfigFilter = {
  seo?: ConfigSeoFilter | null | undefined;
  nav?: ConfigNavFilter | null | undefined;
  footerNote?: StringFilter | null | undefined;
};

export type PagePartsFragment = { __typename: 'Page', seoTitle: string, blocks: Array<
    | { __typename: 'PageBlocksHero', eyebrow: string | null, headline: string | null, tagline: string | null, primaryAction: { __typename: 'PageBlocksHeroPrimaryAction', label: string | null, link: string | null } | null, secondaryAction: { __typename: 'PageBlocksHeroSecondaryAction', label: string | null, link: string | null } | null, image: { __typename: 'PageBlocksHeroImage', src: string | null, alt: string | null } | null }
    | { __typename: 'PageBlocksRichText', eyebrow: string | null, headline: string | null, body: TinaMarkdownContent | null }
    | { __typename: 'PageBlocksMedia', aspect: string | null, image: { __typename: 'PageBlocksMediaImage', src: string | null, alt: string | null, caption: string | null } | null }
    | { __typename: 'PageBlocksCta', headline: string | null, text: string | null, primaryLabel: string | null, primaryLink: string | null, secondaryLabel: string | null, secondaryLink: string | null }
    | { __typename: 'PageBlocksGallery', headline: string | null, images: Array<{ __typename: 'PageBlocksGalleryImages', src: string | null, alt: string | null, caption: string | null } | null> | null }
    | { __typename: 'PageBlocksAccordion', headline: string | null, items: Array<{ __typename: 'PageBlocksAccordionItems', title: string | null, content: TinaMarkdownContent | null } | null> | null }
    | { __typename: 'PageBlocksStats', headline: string | null, items: Array<{ __typename: 'PageBlocksStatsItems', value: string | null, label: string | null } | null> | null }
    | { __typename: 'PageBlocksTestimonial', quote: string | null, author: string | null, role: string | null, avatar: { __typename: 'PageBlocksTestimonialAvatar', src: string | null, alt: string | null } | null }
    | { __typename: 'PageBlocksPricing', eyebrow: string | null, headline: string | null, subhead: string | null, accent: string | null, fine: string | null, tiers: Array<{ __typename: 'PageBlocksPricingTiers', title: string | null, price: string | null, priceNote: string | null, desc: string | null, bullets: Array<string | null> | null, featured: boolean | null, ctaLabel: string | null, ctaLink: string | null } | null> | null }
   | null> | null };

export type ConfigPartsFragment = { __typename: 'Config', footerNote: string | null, seo: { __typename: 'ConfigSeo', title: string, description: string } | null, nav: Array<{ __typename: 'ConfigNav', title: string, link: string } | null> | null };

export type PageQueryVariables = Exact<{
  relativePath: string;
}>;


export type PageQuery = { page: { __typename: 'Page', id: string, seoTitle: string, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, blocks: Array<
      | { __typename: 'PageBlocksHero', eyebrow: string | null, headline: string | null, tagline: string | null, primaryAction: { __typename: 'PageBlocksHeroPrimaryAction', label: string | null, link: string | null } | null, secondaryAction: { __typename: 'PageBlocksHeroSecondaryAction', label: string | null, link: string | null } | null, image: { __typename: 'PageBlocksHeroImage', src: string | null, alt: string | null } | null }
      | { __typename: 'PageBlocksRichText', eyebrow: string | null, headline: string | null, body: TinaMarkdownContent | null }
      | { __typename: 'PageBlocksMedia', aspect: string | null, image: { __typename: 'PageBlocksMediaImage', src: string | null, alt: string | null, caption: string | null } | null }
      | { __typename: 'PageBlocksCta', headline: string | null, text: string | null, primaryLabel: string | null, primaryLink: string | null, secondaryLabel: string | null, secondaryLink: string | null }
      | { __typename: 'PageBlocksGallery', headline: string | null, images: Array<{ __typename: 'PageBlocksGalleryImages', src: string | null, alt: string | null, caption: string | null } | null> | null }
      | { __typename: 'PageBlocksAccordion', headline: string | null, items: Array<{ __typename: 'PageBlocksAccordionItems', title: string | null, content: TinaMarkdownContent | null } | null> | null }
      | { __typename: 'PageBlocksStats', headline: string | null, items: Array<{ __typename: 'PageBlocksStatsItems', value: string | null, label: string | null } | null> | null }
      | { __typename: 'PageBlocksTestimonial', quote: string | null, author: string | null, role: string | null, avatar: { __typename: 'PageBlocksTestimonialAvatar', src: string | null, alt: string | null } | null }
      | { __typename: 'PageBlocksPricing', eyebrow: string | null, headline: string | null, subhead: string | null, accent: string | null, fine: string | null, tiers: Array<{ __typename: 'PageBlocksPricingTiers', title: string | null, price: string | null, priceNote: string | null, desc: string | null, bullets: Array<string | null> | null, featured: boolean | null, ctaLabel: string | null, ctaLink: string | null } | null> | null }
     | null> | null } };

export type PageConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: PageFilter | null | undefined;
}>;


export type PageConnectionQuery = { pageConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Page', id: string, seoTitle: string, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, blocks: Array<
          | { __typename: 'PageBlocksHero', eyebrow: string | null, headline: string | null, tagline: string | null, primaryAction: { __typename: 'PageBlocksHeroPrimaryAction', label: string | null, link: string | null } | null, secondaryAction: { __typename: 'PageBlocksHeroSecondaryAction', label: string | null, link: string | null } | null, image: { __typename: 'PageBlocksHeroImage', src: string | null, alt: string | null } | null }
          | { __typename: 'PageBlocksRichText', eyebrow: string | null, headline: string | null, body: TinaMarkdownContent | null }
          | { __typename: 'PageBlocksMedia', aspect: string | null, image: { __typename: 'PageBlocksMediaImage', src: string | null, alt: string | null, caption: string | null } | null }
          | { __typename: 'PageBlocksCta', headline: string | null, text: string | null, primaryLabel: string | null, primaryLink: string | null, secondaryLabel: string | null, secondaryLink: string | null }
          | { __typename: 'PageBlocksGallery', headline: string | null, images: Array<{ __typename: 'PageBlocksGalleryImages', src: string | null, alt: string | null, caption: string | null } | null> | null }
          | { __typename: 'PageBlocksAccordion', headline: string | null, items: Array<{ __typename: 'PageBlocksAccordionItems', title: string | null, content: TinaMarkdownContent | null } | null> | null }
          | { __typename: 'PageBlocksStats', headline: string | null, items: Array<{ __typename: 'PageBlocksStatsItems', value: string | null, label: string | null } | null> | null }
          | { __typename: 'PageBlocksTestimonial', quote: string | null, author: string | null, role: string | null, avatar: { __typename: 'PageBlocksTestimonialAvatar', src: string | null, alt: string | null } | null }
          | { __typename: 'PageBlocksPricing', eyebrow: string | null, headline: string | null, subhead: string | null, accent: string | null, fine: string | null, tiers: Array<{ __typename: 'PageBlocksPricingTiers', title: string | null, price: string | null, priceNote: string | null, desc: string | null, bullets: Array<string | null> | null, featured: boolean | null, ctaLabel: string | null, ctaLink: string | null } | null> | null }
         | null> | null } | null } | null> | null } };

export type ConfigQueryVariables = Exact<{
  relativePath: string;
}>;


export type ConfigQuery = { config: { __typename: 'Config', id: string, footerNote: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, seo: { __typename: 'ConfigSeo', title: string, description: string } | null, nav: Array<{ __typename: 'ConfigNav', title: string, link: string } | null> | null } };

export type ConfigConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: ConfigFilter | null | undefined;
}>;


export type ConfigConnectionQuery = { configConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Config', id: string, footerNote: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, seo: { __typename: 'ConfigSeo', title: string, description: string } | null, nav: Array<{ __typename: 'ConfigNav', title: string, link: string } | null> | null } | null } | null> | null } };

export const PagePartsFragmentDoc = gql`
    fragment PageParts on Page {
  __typename
  seoTitle
  blocks {
    __typename
    ... on PageBlocksHero {
      eyebrow
      headline
      tagline
      primaryAction {
        __typename
        label
        link
      }
      secondaryAction {
        __typename
        label
        link
      }
      image {
        __typename
        src
        alt
      }
    }
    ... on PageBlocksRichText {
      eyebrow
      headline
      body
    }
    ... on PageBlocksMedia {
      image {
        __typename
        src
        alt
        caption
      }
      aspect
    }
    ... on PageBlocksCta {
      headline
      text
      primaryLabel
      primaryLink
      secondaryLabel
      secondaryLink
    }
    ... on PageBlocksGallery {
      headline
      images {
        __typename
        src
        alt
        caption
      }
    }
    ... on PageBlocksAccordion {
      headline
      items {
        __typename
        title
        content
      }
    }
    ... on PageBlocksStats {
      headline
      items {
        __typename
        value
        label
      }
    }
    ... on PageBlocksTestimonial {
      quote
      author
      role
      avatar {
        __typename
        src
        alt
      }
    }
    ... on PageBlocksPricing {
      eyebrow
      headline
      subhead
      accent
      tiers {
        __typename
        title
        price
        priceNote
        desc
        bullets
        featured
        ctaLabel
        ctaLink
      }
      fine
    }
  }
}
    `;
export const ConfigPartsFragmentDoc = gql`
    fragment ConfigParts on Config {
  __typename
  seo {
    __typename
    title
    description
  }
  nav {
    __typename
    title
    link
  }
  footerNote
}
    `;
export const PageDocument = gql`
    query page($relativePath: String!) {
  page(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PageParts
  }
}
    ${PagePartsFragmentDoc}`;
export const PageConnectionDocument = gql`
    query pageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PageFilter) {
  pageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PageParts
      }
    }
  }
}
    ${PagePartsFragmentDoc}`;
export const ConfigDocument = gql`
    query config($relativePath: String!) {
  config(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ConfigParts
  }
}
    ${ConfigPartsFragmentDoc}`;
export const ConfigConnectionDocument = gql`
    query configConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ConfigFilter) {
  configConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ConfigParts
      }
    }
  }
}
    ${ConfigPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      page(variables: PageQueryVariables, options?: C): Promise<{data: PageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageQueryVariables, query: string}> {
        return requester<{data: PageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageQueryVariables, query: string}, PageQueryVariables>(PageDocument, variables, options);
      },
    pageConnection(variables?: PageConnectionQueryVariables, options?: C): Promise<{data: PageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageConnectionQueryVariables, query: string}> {
        return requester<{data: PageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageConnectionQueryVariables, query: string}, PageConnectionQueryVariables>(PageConnectionDocument, variables, options);
      },
    config(variables: ConfigQueryVariables, options?: C): Promise<{data: ConfigQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ConfigQueryVariables, query: string}> {
        return requester<{data: ConfigQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ConfigQueryVariables, query: string}, ConfigQueryVariables>(ConfigDocument, variables, options);
      },
    configConnection(variables?: ConfigConnectionQueryVariables, options?: C): Promise<{data: ConfigConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ConfigConnectionQueryVariables, query: string}> {
        return requester<{data: ConfigConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ConfigConnectionQueryVariables, query: string}, ConfigConnectionQueryVariables>(ConfigConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "https://content.tinajs.io/3.0/content/829b3911-5d84-44ed-b44b-280957b14b71/github/main",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

export type { Exact };

  