name = "trade-demos-astro"
account_id = "cbf48c78b17effd556df217fadc93cde"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[vars]
SITE_URL = "https://trade-demos-astro.akarshbandi82.workers.dev"
